title: JediComp
author: Thiago 'Jedi' Abreu

repository: thiagoabreu/thiagoabreu.github.io

lang: pt_BR
timezone: America/Recife
markdown: CommonMarkGhPages

paginate_path: "blog/page:num/"
paginate: 3

permalink: none

plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - .gitignore
  - .git
  - taste.bat
  - Pretzel.exe
  - vendor
  - .idea

image: https://github.com/thiagoabreu.png

twitter:
  username: Jedi_Thiago

social:
  name: Thiago 'Jedi' Abreu
  links:
    - https://twitter.com/Jedi_Thiago
    - https://fb.com/thiagojedi
    - https://github.com/thiagoabreu

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]