title: JediComp
author: Thiago 'Jedi' Abreu

lang: pt_BR
timezone: America/Recife
markdown: kramdown

paginate_path: "blog/page:num/"
paginate: 3

permalink: none

plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - bootstrap\less\
  - .gitignore
  - .git
  - taste.bat
  - Pretzel.exe

image: https://github.com/thiagoabreu.png

twitter:
  username: Jedi_Thiago

social:
    name: Thiago 'Jedi' Abreu
    links:
      - https://twitter.com/Jedi_Thiago
      - https://fb.com/thiagojedi
      - https://github.com/thiagoabreu
