timezone: America/Recife
markdown: kramdown

paginate_path: "blog/page:num/"
paginate: 3

permalink: none

gems:
  - jekyll-mentions
  - jekyll-paginate

exclude:
  - bootstrap\less\
  - .gitignore
  - .git
  - taste.bat
  - Pretzel.exe