timezone: America/Recife
markdown: kramdown

paginate_path: "blog/page:num"
paginate: 5

permalink: none

category_archive:
   path: blog

exclude:
  - bootstrap\less\
  - .gitignore
  - .git
  - taste.bat
  - Pretzel.exe