timezone: America/Recife
markdown: kramdown

paginate_path: "blog/page:num/"
paginate: 3

permalink: none

gems:
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-auto-image
  - jemoji

exclude:
  - bootstrap\less\
  - .gitignore
  - .git
  - taste.bat
  - Pretzel.exe

image: https://github.com/thiagoabreu.png